export const users = [
  {
    email: "renzifebriadnika@mail.com",
    username: "renzi",
    role: "admin",
    password: "bpsmitra",
  },
  {
    email: "popiaekaputri4@gmail.com",
    username: "popiaekaputri4",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "anggidewirahmat98@gmail.com",
    username: "anggidewirahmat98",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "eranoviarti18@gmail.com",
    username: "eranoviarti18",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "yulianirinesa@gmail.com",
    username: "yulianirinesa",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "diajengdealova@gmail.com",
    username: "diajengdealova",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "elvimaulidaputri1623@gmail.com",
    username: "elvimaulidaputri1623",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "lailatulbadriah482@gmail.com",
    username: "lailatulbadriah482",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "soniarahayu1201@gmail.com",
    username: "soniarahayu1201",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "azmikhoirani9@gmail.com",
    username: "azmikhoirani9",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "muliatiajja17@gmail.com",
    username: "muliatiajja17",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "widiwulandari459@gmail.com",
    username: "widiwulandari459",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "syahrawani2@gmail.com",
    username: "syahrawani2",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "fitriannisa058@gmail.com",
    username: "fitriannisa058",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "sarinurmela087@gmail.com",
    username: "sarinurmela087",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "maisarohmtd05@gmail.com",
    username: "maisarohmtd05",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "asrilr49@gmail.com",
    username: "asrilr49",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Sri1702mun@gmail.com",
    username: "Sri1702mun",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "mulyanti658@gmail.com",
    username: "mulyanti658",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "laurenciavalery81@gmail.com",
    username: "laurenciavalery81",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "elmar.yuknia.s@gmail.com",
    username: "elmar.yuknia.s",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "aridaa730@gmail.com",
    username: "aridaa730",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "harmi.rainaputri@gmail.com",
    username: "harmi.rainaputri",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "denisartika121@gmail.com",
    username: "denisartika121",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "riendo1111@gmail.com",
    username: "riendo1111",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "suspitahelmi87@gmail.com",
    username: "suspitahelmi87",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "niasafitri784@gmail.com",
    username: "niasafitri784",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "eragusnita677@gmail.com",
    username: "eragusnita677",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "rahmialisputri2@gmail.com",
    username: "rahmialisputri2",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "sabta.nst27031994@gmail.com",
    username: "sabta.nst27031994",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "yuniitalestaria@gmail.com",
    username: "yuniitalestaria",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Indahjasminehendrri@gmail.com",
    username: "Indahjasminehendrri",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "nsuwitapertiwi@gmail.com",
    username: "nsuwitapertiwi",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "hartatiwirda07@gmail.com",
    username: "hartatiwirda07",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "anita567sari@gmail.com",
    username: "anita567sari",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "yulisranlubis@gmail.com",
    username: "yulisranlubis",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "kpunduang16@gmail.com",
    username: "kpunduang16",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "annisajuliantii037@gmail.com",
    username: "annisajuliantii037",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "niaasniati47@gmail.com",
    username: "niaasniati47",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "bobiyuliandra9@gmail.com",
    username: "bobiyuliandra9",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "elikosma56@gmail.com",
    username: "elikosma56",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "annisahudria06@gmail.com",
    username: "annisahudria06",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "satdipal.anjuja8@gmail.com",
    username: "satdipal.anjuja8",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "ella.monika10@gmail.com",
    username: "ella.monika10",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Irfansarasah@gmail.com",
    username: "Irfansarasah",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "alamguntur711@gmail.com",
    username: "alamguntur711",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "fitrayulia527@gmail.com",
    username: "fitrayulia527",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "niaanora@gmail.com",
    username: "niaanora",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "ainilmatondang96@gmail.com",
    username: "ainilmatondang96",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Asdarsyah63@gmail.com",
    username: "Asdarsyah63",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "zulitapsi@gmail.com",
    username: "zulitapsi",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "apriaries87@gmail.com",
    username: "apriaries87",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "wirnaw527@gmail.com",
    username: "wirnaw527",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "jekis6986@gmail.com",
    username: "jekis6986",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "roliafriyanti08@gmail.com",
    username: "roliafriyanti08",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "everariska@gmail.com",
    username: "everariska",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "tidarti@gmail.com",
    username: "tidarti",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "nadianovemi09@gmail.com",
    username: "nadianovemi09",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "maysyaroh0405@gmail.com",
    username: "maysyaroh0405",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "depiyarni22@gmail.com",
    username: "depiyarni22",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Dewisafitri470@gmail.com",
    username: "Dewisafitri470",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "nunuoces278@gmail.com",
    username: "nunuoces278",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "sitiarniati95@gmail.com",
    username: "sitiarniati95",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "nurainun180303@gmail.com",
    username: "nurainun180303",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "abdianfachtrisya@gmail.com",
    username: "abdianfachtrisya",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "harmendi0599@gmail.com",
    username: "harmendi0599",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "rizkymaritolubis@gmail.com",
    username: "rizkymaritolubis",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "elizafatmawati1@gmail.com",
    username: "elizafatmawati1",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "anhasofia27@gmail.com",
    username: "anhasofia27",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "realmemitra9@gmail.com",
    username: "realmemitra9",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "sudrohasnah@gmail.com",
    username: "sudrohasnah",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Rosfariani5@gmail.com",
    username: "Rosfariani5",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "dian.lestari782@yahoo.co.id",
    username: "dian.lestari782",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "safitrianisa321@gmail.com",
    username: "safitrianisa321",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "yuliayul100594@gmail.com",
    username: "yuliayul100594",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "apridayenni2121@gmail.com",
    username: "apridayenni2121",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "ritharadiatul7@gmail.com",
    username: "ritharadiatul7",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "yusniatiima286@gmail.com",
    username: "yusniatiima286",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "delamonica615@gmail.com",
    username: "delamonica615",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "meirisatiarani43@gmail.com",
    username: "meirisatiarani43",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "metriakhanza@gmail.com",
    username: "metriakhanza",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Musrizalpulaupanjang@gmail.com",
    username: "Musrizalpulaupanjang",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Zamlison86@gmail.com",
    username: "Zamlison86",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "triaagustin027@gmail.com",
    username: "triaagustin027",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "abinechannels@gmail.com",
    username: "abinechannels",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Akipyupendra796@gmail.com",
    username: "Akipyupendra796",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "nofenrizal123@gmail.com",
    username: "nofenrizal123",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "azhariahfatia10@gmail.com",
    username: "azhariahfatia10",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "mutiahummi937@gmail.com",
    username: "mutiahummi937",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "wahyuni100198@gmail.com",
    username: "wahyuni100198",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "ronasari280608@gmail.com",
    username: "ronasari280608",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Yonalfitra123@gmail.com",
    username: "Yonalfitra123",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "fitrimelini4@gmail.com",
    username: "fitrimelini4",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "afniniasarii@gmail.com",
    username: "afniniasarii",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "spyaekaputriii18@gmail.com",
    username: "spyaekaputriii18",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Izasafitri.id@gmail.com",
    username: "Izasafitri.id",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "salmi17041996@gmail.com",
    username: "salmi17041996",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "fikriejambak@gmail.com",
    username: "fikriejambak",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "fadhillanaufalahmad@gmail.com",
    username: "fadhillanaufalahmad",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "mutiahzahra1212@gmail.com",
    username: "mutiahzahra1212",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "eliaroza1999@gmail.com",
    username: "eliaroza1999",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "silpasbar@gmail.com",
    username: "silpasbar",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Dewimurtidesi@gmail.com",
    username: "Dewimurtidesi",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "dyalagee7@gmail.com",
    username: "dyalagee7",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "syahyudi337@gmail.com",
    username: "syahyudi337",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "fatimahamini20@gmail.com",
    username: "fatimahamini20",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "yessisofiana1201@gmail.com",
    username: "yessisofiana1201",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Wahyufitrianingsih.01@gmail.com",
    username: "Wahyufitrianingsih.01",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "yonggiseptapramadia16@gmail.com",
    username: "yonggiseptapramadia16",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "al0852nst@gmail.com",
    username: "al0852nst",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Is8997413@gmail.com",
    username: "Is8997413",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "nisakutrianingsih207@gmail.com",
    username: "nisakutrianingsih207",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "mella.angreani2006@gmail.com",
    username: "mella.angreani2006",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "romifitra9@gmail.com",
    username: "romifitra9",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "dwi.lestary.s123@gmail.com",
    username: "dwi.lestary.s123",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "w1nsky1982@gmail.com",
    username: "w1nsky1982",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "nadamartilofa20@gmail.com",
    username: "nadamartilofa20",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "lubismursallubis@gmail.com",
    username: "lubismursallubis",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "almiami37@gmail.com",
    username: "almiami37",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "indraowen0609@gmail.com",
    username: "indraowen0609",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "ryanyuzalmi@gmail.com",
    username: "ryanyuzalmi",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "annisazilhayati7@gmail.com",
    username: "annisazilhayati7",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "andriaprisandra0604@gmail.com",
    username: "andriaprisandra0604",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "sriwahyni06@gmail.com",
    username: "sriwahyni06",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Sofyanhuda18@gmail.com",
    username: "Sofyanhuda18",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "widyawidyasetyaningsih@gmail.com",
    username: "widyawidyasetyaningsih",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "mesrawaticandra14@gmail.com",
    username: "mesrawaticandra14",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "ritamaryeni452@gmail.com",
    username: "ritamaryeni452",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "riska6900@gmail.com",
    username: "riska6900",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "lenyangreini2506@gmail.com",
    username: "lenyangreini2506",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Chanalfajrei94@gmail.com",
    username: "Chanalfajrei94",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "raniifebiola05@gmail.com",
    username: "raniifebiola05",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "riki.susanto2893@gmail.com",
    username: "riki.susanto2893",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "witrihndy05@gmail.com",
    username: "witrihndy05",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "gusnidarbatubara@yahoo.com",
    username: "gusnidarbatubara",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "me.taufik@gmail.com",
    username: "me.taufik",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Pasamaneti@gmail.com",
    username: "Pasamaneti",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "tiaradesthyafrina@gmail.com",
    username: "tiaradesthyafrina",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "vivizahara15@gmail.com",
    username: "vivizahara15",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Diahnitaretnasari@gmail.com",
    username: "Diahnitaretnasari",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "desvitafamela@gmail.com",
    username: "desvitafamela",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "mutiahafifah@gmail.com",
    username: "mutiahafifah",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "luthficorbuzier@gmail.com",
    username: "luthficorbuzier",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "windyutri1003@gmail.com",
    username: "windyutri1003",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Isramaria902@gmail.com",
    username: "Isramaria902",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "syahasdar@gmail.com",
    username: "syahasdar",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "nauliasmita19@gmail.com",
    username: "nauliasmita19",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "fanielwista@gmail.com",
    username: "fanielwista",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "tafa.mrahman@gmail.com",
    username: "tafa.mrahman",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "srina7760@gmail.com",
    username: "srina7760",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "karmerifa15@gmail.com",
    username: "karmerifa15",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "dianatashaf19@gmail.com",
    username: "dianatashaf19",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "helizarahmi0@gmail.com",
    username: "helizarahmi0",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "yodrialkaroz01@gmail.com",
    username: "yodrialkaroz01",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "elvitriana09@gmail.com",
    username: "elvitriana09",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "sastikadwy@gmail.com",
    username: "sastikadwy",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "irmahelmiani@gmail.com",
    username: "irmahelmiani",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "lusi.mardiah96@gmail.com",
    username: "lusi.mardiah96",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "indahrahayumelati@gmail.com",
    username: "indahrahayumelati",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "meiracitralegina@gmail.com",
    username: "meiracitralegina",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "riskanurvadila44@gmail.com",
    username: "riskanurvadila44",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "soniadora50@gmail.com",
    username: "soniadora50",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "sncomputerdly@gmail.com",
    username: "sncomputerdly",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "rezielizafebri@gmail.com",
    username: "rezielizafebri",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "frensiskaana@yahoo.com",
    username: "frensiskaana",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "cahaya.yhati72@gmail.com",
    username: "cahaya.yhati72",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "desniatidesni879@gmail.com",
    username: "desniatidesni879",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "mellzaa22mel@gmail.com",
    username: "mellzaa22mel",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "febimardhotillah3@gmail.com",
    username: "febimardhotillah3",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Jonisajolubis@gmail.com",
    username: "Jonisajolubis",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "ilvasepti5@gmail.com",
    username: "ilvasepti5",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "pebniasih@gmail.com",
    username: "pebniasih",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "yusep.ahadi@gmail.com",
    username: "yusep.ahadi",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "nofrisonlubis91@gmail.com",
    username: "nofrisonlubis91",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "dwiauliarahmi13@gmail.com",
    username: "dwiauliarahmi13",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "nofrizariza28@gmail.com",
    username: "nofrizariza28",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "hilpanriyanto@gmail.com",
    username: "hilpanriyanto",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "bluedoser270@gmail.com",
    username: "bluedoser270",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Raninovika96@gmail.com",
    username: "Raninovika96",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "hartatiayumi3@gmail.com",
    username: "hartatiayumi3",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "welnasuprini5@gmail.com",
    username: "welnasuprini5",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "fitriamandasari0505@gmail.com",
    username: "fitriamandasari0505",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "nuraisyahrahmadani51@gmail.com",
    username: "nuraisyahrahmadani51",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "sitidumakarmila01@gmail.com",
    username: "sitidumakarmila01",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "fitriayulista01@gmail.com",
    username: "fitriayulista01",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "melliarozam@gmail.com",
    username: "melliarozam",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "nurhamida1412@gmail.com",
    username: "nurhamida1412",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "robiagusman45@gmail.com",
    username: "robiagusman45",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "rnmi182@gmail.com",
    username: "rnmi182",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "lenialisputri95@gmail.com",
    username: "lenialisputri95",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "raisalfarizi19@gmail.com",
    username: "raisalfarizi19",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "daniatineneng857@gmail.com",
    username: "daniatineneng857",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "cicifatasia@gmail.com",
    username: "cicifatasia",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "najminst@gmail.com",
    username: "najminst",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Gustirahmat0108@gmail.com",
    username: "Gustirahmat0108",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "mitarvd09@gmail.com",
    username: "mitarvd09",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Iinherlisa4@gmail.com",
    username: "Iinherlisa4",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "adesunarsih900@gmail.com",
    username: "adesunarsih900",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "mesiutami960@gmail.com",
    username: "mesiutami960",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "muhammadikon20@gmail.com",
    username: "muhammadikon20",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "anissqiva@gmail.com",
    username: "anissqiva",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "putraadimarta@gmail.com",
    username: "putraadimarta",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "irma76633@gmail.com",
    username: "irma76633",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "nurmaindri27januari@gmail.com",
    username: "nurmaindri27januari",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "zulpyalubis1992@gmail.com",
    username: "zulpyalubis1992",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "faulaannisa301@gmail.com",
    username: "faulaannisa301",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "jejakmasendo@gmail.com",
    username: "jejakmasendo",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "novasafitri329@gmail.com",
    username: "novasafitri329",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "oz.axeyz@gmail.com",
    username: "oz.axeyz",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Www.sutarno18@gmail.com",
    username: "Www.sutarno18",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "wardani8227@gmail.com",
    username: "wardani8227",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "risma1906wati@gmail.com",
    username: "risma1906wati",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "ulyasafitri2404@gmail.com",
    username: "ulyasafitri2404",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "hutajuluginta9@gmail.com",
    username: "hutajuluginta9",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "aidasofiani466@gmail.com",
    username: "aidasofiani466",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "fajriakamila05@gmail.com",
    username: "fajriakamila05",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "desise6@gmail.com",
    username: "desise6",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "nuralisa761@gmail.com",
    username: "nuralisa761",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "etika.diana92@gmail.com",
    username: "etika.diana92",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "nanda.saputra0733@gmail.com",
    username: "nanda.saputra0733",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "yunusmuhammad990@gmail.com",
    username: "yunusmuhammad990",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Fy2315601@gmail.com",
    username: "Fy2315601",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "nurjannah11oktober1998@gmail.com",
    username: "nurjannah11oktober1998",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "rezkiindah02@gmail.com",
    username: "rezkiindah02",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "rizkyarmanda916@gmail.com",
    username: "rizkyarmanda916",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "alfazrosita@gmail.com",
    username: "alfazrosita",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "krisdiantoyohanes251@gmail.com",
    username: "krisdiantoyohanes251",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "yutrimarianti212@gmail.com",
    username: "yutrimarianti212",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Dirsima05@gmail.com",
    username: "Dirsima05",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "afriayolanda@gmail.com",
    username: "afriayolanda",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "nadyarahmasuwanti490@gmail.com",
    username: "nadyarahmasuwanti490",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "dianmusaropah28@gmail.com",
    username: "dianmusaropah28",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Nurmahidayat829@gmail.com",
    username: "Nurmahidayat829",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Meirina.tetty487@gmail.com",
    username: "Meirina.tetty487",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "asharsati1981@gmail.com",
    username: "asharsati1981",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "hadizul322@gmail.com",
    username: "hadizul322",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "wafdaajah055@gmail.com",
    username: "wafdaajah055",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "rimacleoriez9044@gmail.com",
    username: "rimacleoriez9044",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "arsitasari93@gmail.com",
    username: "arsitasari93",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "ainunzuhriah20@gmail.com",
    username: "ainunzuhriah20",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "fitriaasya8@gmail.com",
    username: "fitriaasya8",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Elfianti132@gmail.com",
    username: "Elfianti132",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Syahdahadianta@gmail.com",
    username: "Syahdahadianta",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "srimhrni06@gmail.com",
    username: "srimhrni06",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "nurulananda310@gmail.com",
    username: "nurulananda310",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "zdaini29@gmail.com",
    username: "zdaini29",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "Andarayurniw@gmail.com",
    username: "Andarayurniw",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "afnitanoly@gmail.com",
    username: "afnitanoly",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "yayangangelabungsu@gmail.com",
    username: "yayangangelabungsu",
    role: "user",
    password: "bpsmitra",
  },
  {
    email: "aayu02181@gmail.com",
    username: "aayu02181",
    role: "user",
    password: "bpsmitra",
  },
];
